version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
      include: "scope"

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
    labels:
      - "go"

  - package-ecosystem: "npm"
    directories:
      - "/docs"
      - "/js/ga4-duplicator"
      - "/js/web-tracker"
    patterns:
      - "*"
    multi-ecosystem-group: "all-dependencies"
    labels:
      - "javascript"
