version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - forbidigo
    - forcetypeassert
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - gosec
    - govet
    - lll
    - misspell
    - nakedret
    - nilnil
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
    - whitespace
  settings:
    depguard:
      rules:
        Main:
          list-mode: lax
          files:
            - $all
            - '!$test'
          deny:
            - pkg: reflect
              desc: Please don't use reflect package
    dupl:
      threshold: 95
    errorlint:
      errorf: true
      asserts: true
      comparison: true
    exhaustive:
      default-signifies-exhaustive: true
    forbidigo:
      forbid:
        - pattern: '&IdentifierConflictRequest\{'
          msg: use NewIdentifierConflictRequest constructor instead of direct struct instantiation
        - pattern: '&IdentifierConflictResponse\{'
          msg: use NewIdentifierConflictResponse constructor instead of direct struct instantiation
        - pattern: '&AppendHitsToProtoSessionRequest\{'
          msg: use NewAppendHitsToProtoSessionRequest constructor instead of direct struct instantiation
        - pattern: '&AppendHitsToProtoSessionResponse\{'
          msg: use NewAppendHitsToProtoSessionResponse constructor instead of direct struct instantiation
        - pattern: '&GetProtoSessionHitsRequest\{'
          msg: use NewGetProtoSessionHitsRequest constructor instead of direct struct instantiation
        - pattern: '&GetProtoSessionHitsResponse\{'
          msg: use NewGetProtoSessionHitsResponse constructor instead of direct struct instantiation
        - pattern: '&RemoveProtoSessionHitsRequest\{'
          msg: use NewRemoveProtoSessionHitsRequest constructor instead of direct struct instantiation
        - pattern: '&RemoveProtoSessionHitsResponse\{'
          msg: use NewRemoveProtoSessionHitsResponse constructor instead of direct struct instantiation
        - pattern: '&RemoveAllHitRelatedMetadataRequest\{'
          msg: use NewRemoveAllHitRelatedMetadataRequest constructor instead of direct struct instantiation
        - pattern: '&RemoveAllHitRelatedMetadataResponse\{'
          msg: use NewRemoveAllHitRelatedMetadataResponse constructor instead of direct struct instantiation
        - pattern: '&MarkProtoSessionClosingForGivenBucketRequest\{'
          msg: use NewMarkProtoSessionClosingForGivenBucketRequest constructor instead of direct struct instantiation
        - pattern: '&MarkProtoSessionClosingForGivenBucketResponse\{'
          msg: use NewMarkProtoSessionClosingForGivenBucketResponse constructor instead of direct struct instantiation
        - pattern: '&GetAllProtosessionsForBucketRequest\{'
          msg: use NewGetAllProtosessionsForBucketRequest constructor instead of direct struct instantiation
        - pattern: '&GetAllProtosessionsForBucketResponse\{'
          msg: use NewGetAllProtosessionsForBucketResponse constructor instead of direct struct instantiation
    funlen:
      lines: 85
      statements: 60
    gocognit:
      min-complexity: 50
    goconst:
      min-occurrences: 4
    gocritic:
      disabled-checks:
        - unlambda
        - importShadow
      enabled-tags:
        - diagnostic
        - style
        - performance
    gosec:
      excludes:
        - G104
    lll:
      line-length: 120
    nakedret:
      max-func-lines: 30
    perfsprint:
      error-format: true
      string-format: true
    revive:
      rules:
        - name: var-naming
          disabled: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - funlen
          - gosec
          - gocognit
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$